version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=b4oy5b3is5h6dec1htr6-mysql.services.clever-cloud.com
      - DB_USER=uno7rxvxj0nqpecb
      - DB_PASSWORD=9WpgCnTLvsEA71yBsfTm
      - DB_NAME=b4oy5b3is5h6dec1htr6
    networks:
      - employee-app-network

  frontend:
    build: 
      context: ./frontend/FormValidationProj
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - employee-app-network


networks:
  employee-app-network: